id: PD464B634
initial_creation_type: ocr
source_metadata:
  volumes:
    80d0b2dc63af49fe9f08df8207c93787:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
