id: PD464B634
initial_creation_type: ocr
source_metadata:
  volumes:
    a22d4f98402e4b6bb9084573a9eacd61:
      base_file: v075.txt
      image_group_id: I1PD95920
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1529
      volume_number: 75
